spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booksdb
    username: vyachic007
    password: mtba0374
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true